FROM debian:jessie
MAINTAINER Edgar Garriga <edgano@gmail.com>

## 'edgano/tcoffee:protocols'
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      ed \
      less \
      vim-tiny \
      wget \
      git \
      python \
      build-essential \
      cmake \
      curl \
      libargtable2-0 \
      ca-certificates \
      libpng12-0 \
      python-biopython \
      python-numpy \ 
      ruby \ 
      python-setuptools \
      default-jdk \
      valgrind \
      libpng-dev \
      gfortran

# Install BLAST+
RUN wget https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ncbi-blast-2.10.0+-x64-linux.tar.gz && \
    tar xvf ncbi-blast-2.10.0+-x64-linux.tar.gz && \
    cp ncbi-blast-2.10.0+/bin/* /usr/bin/.

# Install PDB DDBB
RUN mkdir -p /database/pdb && \
    cd /database/pdb && \
    wget ftp://ftp.wwpdb.org/pub/pdb/derived_data/pdb_seqres.txt && \
    makeblastdb -in pdb_seqres.txt -input_type fasta -dbtype prot

# Install Kalign2
RUN wget http://msa.sbc.su.se/downloads/kalign/current.tar.gz && \
    mkdir kalign2 && \
    tar -xzvf current.tar.gz -C kalign2 && \
    cd kalign2 && \
    ./configure && \
    make && \
    mv kalign /bin/.

# Install MUSCLE
RUN wget https://drive5.com/muscle/downloads3.8.31/muscle3.8.31_i86linux32.tar.gz && \
    tar zxf muscle3.8.31_i86linux32.tar.gz && \
    mv muscle3.8.31_i86linux32 muscle && \
    rm muscle3.8.31_i86linux32.tar.gz && \
    mv muscle /bin/

#install fasta35 (needed for mafft)
RUN wget https://faculty.virginia.edu/wrpearson/fasta/fasta33-35/fasta-35.4.12.tar.gz --no-check-certificate && \
    tar -zxf fasta-35.4.12.tar.gz && \
    cd fasta-35.4.12/src && \
    make -f ../make/Makefile.linux_sse2 && \
    cp ../bin/* /bin/. && \
    rm /fasta-35.4.12.tar.gz

# install MAFFT
RUN wget http://mafft.cbrc.jp/alignment/software/mafft-7.397-with-extensions-src.tgz && \
    tar xfvz mafft-7.397-with-extensions-src.tgz && \
    cd mafft-7.397-with-extensions/core/ && \
    sed -i "s/PREFIX = \/usr\/local/PREFIX = \/mafft/g" Makefile && \
    sed -i "s/BINDIR = \$(PREFIX)\/bin/BINDIR = \/mafft\/bin/g" Makefile && \
    make clean && \
    make && \
    make install && \
    wget http://mafft.cbrc.jp/alignment/software/newick2mafft.rb && \
    chmod +x newick2mafft.rb && \
    cp newick2mafft.rb /bin/. && \
    export "PATH=$PATH:/mafft/bin" && \ 
    cp /mafft/bin/* /bin/. && \
    mv /mafft-7.397-with-extensions /mafft && \
    rm /mafft-7.397-with-extensions-src.tgz
 
# Install TMalign
RUN wget https://zhanglab.ccmb.med.umich.edu/TM-align/TMalign.f && \
    gfortran -static -O3 -ffast-math -lm -o TMalign TMalign.f && \
    mv TMalign /bin/.

# Install Mustang
RUN wget http://lcb.infotech.monash.edu.au/mustang/mustang_v3.2.3.tgz &&  \
   tar -zxvf mustang_v3.2.3.tgz && \
   cd MUSTANG_v3.2.3/ && \
   make && \
   cp bin/mustang-3.2.3 /bin/mustang && \
   rm /mustang_v3.2.3.tgz

# install argtable 2 (needed for clustal Omega)
RUN wget http://prdownloads.sourceforge.net/argtable/argtable2-13.tar.gz && \
    tar -zxf argtable2-13.tar.gz && \
    cd argtable2-13 && \
    ./configure && \
    make && \
    make install && \
    rm /argtable2-13.tar.gz

# install CLUSTAL OMEGA
RUN wget http://www.clustal.org/omega/clustal-omega-1.2.4.tar.gz && \
    tar -zxf clustal-omega-1.2.4.tar.gz && \
    cd clustal-omega-1.2.4 && \
    sed -i '1157s/1024/100/' src/clustal/muscle_tree.c && \
    ./configure && \
    make && \
    make install && \
    rm /clustal-omega-1.2.4.tar.gz

#install CLUSTAL w2
RUN wget http://www.clustal.org/download/current/clustalw-2.1.tar.gz && \
    tar -zxf clustalw-2.1.tar.gz && \
    cd clustalw-2.1 && \
    ./configure && \
    make && \
    make install && \
    rm /clustalw-2.1.tar.gz
    
# Install Viena for RNAfold
RUN wget https://www.tbi.univie.ac.at/RNA/download/sourcecode/2_4_x/ViennaRNA-2.4.14.tar.gz && \
    tar -zxvf ViennaRNA-2.4.14.tar.gz && \
    cd ViennaRNA-2.4.14 && \
    ./configure && \
    make && \
    make install

# Install TCOFFEE
RUN git clone https://github.com/cbcrg/tcoffee.git tcoffee && \
    cd tcoffee && \
    git checkout 6a0d31b82326819d4e1683aa3910c37068f5a3b6 && \
    cd t_coffee/src && \
    make t_coffee && \
    cp t_coffee /bin/. && \
    cp t_coffee *.pl /bin/.

ENV HOME '/'

ENV FASTA_4_MAFFT '/bin/fasta35'

ENV HOME_4_TCOFFEE '/tmp/.tcoffee/'
ENV CACHE_4_TCOFFEE '/tmp/.tcoffee/cache'
ENV LOCKDIR_4_TCOFFEE '/tmp/.tcoffee/lock'
ENV TMP_4_TCOFFEE '/tmp/.tcoffee/tmp'
ENV TRASH_4_TCOFFEE '/tmp/.tcoffee/trash'

#unset MAFFT_BINARIES
ENV MAFFT_BINARIES ''

#configure perl5 to BLAST templates
ENV PERL5LIB '/usr/share/perl5:/tcoffee/perl/lib/perl5'